import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Product } from './product.entity';

export enum AliasLocale {
  EN = 'en',
  HI = 'hi',
  OTHER = 'other',
}

export enum AliasSource {
  /** Curated by a mandi admin. */
  ADMIN = 'admin',
  /** Captured automatically when an admin merged a SKU submission. */
  MERGE = 'merge',
  /** Generated by the platform (e.g. brand + name permutations). */
  SYSTEM = 'system',
}

/**
 * Alternative names for a product — the "alt names" that make search work the
 * way shopkeepers actually talk. "आटा", "atta", "flour" and "gehu ka atta"
 * should all reach the same product.
 *
 * `normalised` is a lowercased, whitespace-collapsed copy used for matching,
 * so lookups never depend on how the alias was typed.
 */
@Entity('product_aliases')
@Index(['productId'])
@Index(['normalised'])
export class ProductAlias {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => Product, (p) => p.aliases, { onDelete: 'CASCADE' })
  product: Product;

  @Column()
  productId: string;

  @Column()
  alias: string;

  /** Lowercased + whitespace-collapsed form of `alias`, for matching. */
  @Column()
  normalised: string;

  @Column({ type: 'enum', enum: AliasLocale, default: AliasLocale.EN })
  locale: AliasLocale;

  @Column({ type: 'enum', enum: AliasSource, default: AliasSource.ADMIN })
  source: AliasSource;

  @CreateDateColumn()
  createdAt: Date;
}

export function normaliseAlias(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, ' ');
}
